<script lang="ts">
	import Section from '$lib/components/Section.svelte';
	import Container from '$lib/components/Container.svelte';
	import { EyeIcon, ZapIcon, BriefcaseIcon, StarIcon } from 'svelte-feather-icons';

	import { prompt } from '$lib/stores/prompt';
</script>

<Section id="hero">
	<Container>
		<div class="space-y-8 md:space-y-0 md:grid md:grid-cols-2 md:gap-5 lg:gap-10">
			<div>
				<h1>
					3D graphics for your website, <span
						class="text-white inline-block bg-primary rounded-sm p-1 transform rotate-[-2deg] translate-y-2"
						>generated by AI.</span
					>
				</h1>
				<div class="space-y-4 mt-8">
					<textarea
						bind:value={$prompt}
						class="textarea textarea-block resize-none h-32 w-full block bg-backgroundPrimary/60"
						placeholder="A desk setup with a computer, a cup of coffee, and a book."
					/>

					<a href="/generate" class="btn btn-primary btn-xl btn-block">Start Generating</a>
				</div>
			</div>
			<div>
				<div class="grid grid-cols-2 gap-2 transform translate-y-6">
					<img
						src="/render-1.png"
						alt=""
						class="rounded-2xl transform-gpu translate-y-4"
						width={512}
						height={512}
					/>
					<img
						src="/render-2.png"
						alt=""
						class="rounded-2xl transform-gpu -translate-y-4"
						width={512}
						height={512}
					/>
					<img
						src="/render-3.png"
						alt=""
						class="rounded-2xl transform-gpu translate-y-4"
						width={512}
						height={512}
					/>
					<img
						src="/render-4.png"
						alt=""
						class="rounded-2xl transform-gpu -translate-y-4"
						width={512}
						height={512}
					/>
				</div>
			</div>
		</div>
	</Container>
</Section>
<Section id="why-heroify">
	<Container>
		<div class="space-y-6">
			<h2>
				Why <span class="text-white inline-block bg-primary rounded-sm p-1">heroify</span>?
			</h2>

			<div>
				<ul class="grid gap-4 md:grid-cols-2">
					<li>
						<div class="card h-full w-full max-w-max">
							<div class="card-body">
								<div
									class="rounded-full bg-primary w-10 h-10 flex items-center justify-center shadow-lg shadow-primary/30"
								>
									<ZapIcon class="w-6 h-6" />
								</div>
								<h2 class="card-header">Instant turnaround</h2>
								<p class="text-content2">
									With heroify, you can <span class="text-primary"
										>easily create eye-catching visuals with a few clicks</span
									> in just a few minutes!
								</p>
							</div>
						</div>
					</li>
					<li>
						<div class="card h-full max-w-max">
							<div class="card-body">
								<div
									class="rounded-full bg-primary w-10 h-10 flex items-center justify-center shadow-lg shadow-primary/30"
								>
									<EyeIcon class="w-6 h-6" />
								</div>
								<h2 class="card-header">High quality results</h2>
								<p class="text-content2">
									We use specialized prompts and weightings to achieve <span class="text-primary"
										>visually appealing</span
									>
									and
									<span class="text-primary">authentic-looking isometric designs</span>.
								</p>
							</div>
						</div>
					</li>
					<li>
						<div class="card h-full max-w-max">
							<div class="card-body">
								<div
									class="rounded-full bg-primary w-10 h-10 flex items-center justify-center shadow-lg shadow-primary/30"
								>
									<BriefcaseIcon class="w-6 h-6" />
								</div>
								<h2 class="card-header">Full asset ownership</h2>
								<p class="text-content2">
									You can <span class="text-primary">download the generated renders</span> and use them
									however you want. No need to credit heroify!
								</p>
							</div>
						</div>
					</li>
					<li>
						<div class="card h-full max-w-max">
							<div class="card-body">
								<div
									class="rounded-full bg-primary w-10 h-10 flex items-center justify-center shadow-lg shadow-primary/30"
								>
									<StarIcon class="w-6 h-6" />
								</div>
								<h2 class="card-header">Satisfaction Gauranteed</h2>
								<p class="text-content2">
									Use heroify with confidence! If your unsatisified with your results, we'll <span
										class="text-primary">refund your money</span
									>!
								</p>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="flex justify-center">
				<a href="/generate" class="btn btn-primary btn-xl">Start Generating</a>
			</div>
		</div>
	</Container>
</Section>
<Section id="showcase">
	<Container>
		<div>
			<ul class="grid gap-4 md:grid-cols-4">
				<li class="md:transform md:rotate-[2deg]">
					<div class="space-y-6 text-center">
						<img
							class="rounded-2xl shadow-xl shadow-purple-600/30 mx-auto"
							src="/render-5.png"
							alt="A desk with a computer on it"
							width={512}
							height={512}
						/>
						<p class="text-lg font-bold text-content1">
							&#8220;A desk with a computer on it&#8221;
						</p>
					</div>
				</li>
				<li class="md:transform md:rotate-[-2deg]">
					<div class="space-y-6 text-center">
						<img
							class="rounded-2xl shadow-xl shadow-pink-400/30 mx-auto"
							src="/render-6.png"
							alt="A bowl of ramen"
							width={512}
							height={512}
						/>
						<p class="text-lg font-bold text-content1">&#8220;A bowl of ramen&#8221;</p>
					</div>
				</li>
				<li class="md:transform md:rotate-[2deg]">
					<div class="space-y-6 text-center">
						<img
							class="rounded-2xl shadow-xl shadow-emerald-400/30 mx-auto"
							src="/render-7.png"
							alt="A smartphone"
							width={512}
							height={512}
						/>
						<p class="text-lg font-bold text-content1">&#8220;A smartphone&#8221;</p>
					</div>
				</li>
				<li class="md:transform md:rotate-[-2deg]">
					<div class="space-y-6 text-center">
						<img
							class="rounded-2xl shadow-xl border-2 border-white/10 border-dashed mx-auto"
							src="/render-8.png"
							alt="A server rack"
							width={500}
							height={500}
						/>
						<p class="text-lg font-bold text-content1">
							&#8220;A server rack&#8221; (backgroundless coming soon)
						</p>
					</div>
				</li>
			</ul>
		</div>
	</Container>
</Section>
<Section id="faq">
	<Container>
		<div class="space-y-6">
			<div>
				<h2>
					Frequently Asked <span class="text-white inline-block bg-primary rounded-sm p-1"
						>Questions</span
					>
				</h2>
			</div>
			<div class="accordion-group accordion-group-bordered">
				<div class="accordion">
					<input type="checkbox" id="toggle-1" class="accordion-toggle" />
					<label for="toggle-1" class="accordion-title"
						>How many images can I generate with credits</label
					>
					<span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
							><path
								d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"
							/></svg
						>
					</span>
					<div class="accordion-content text-content2 bg-backgroundSecondary">
						<div class="min-h-0">
							1 credit = 1 image. So as long as you have credits, you can generate as many images as
							you want!
						</div>
					</div>
				</div>
				<div class="accordion">
					<input type="checkbox" id="toggle-2" class="accordion-toggle" />
					<label for="toggle-2" class="accordion-title">How much do credits cost?</label>
					<span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
							><path
								d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"
							/></svg
						>
					</span>
					<div class="accordion-content bg-backgroundSecondary">
						<div class="min-h-0">
							We offer credits in three packages. You can purchase 10 credits for $10, 25 credits
							for $20, or 50 credits for $35. All prices are in USD.
						</div>
					</div>
				</div>
				<div class="accordion">
					<input type="checkbox" id="toggle-3" class="accordion-toggle" />
					<label for="toggle-3" class="accordion-title">What payment methods are accepted?</label>
					<span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
							><path
								d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"
							/></svg
						>
					</span>
					<div class="accordion-content bg-backgroundSecondary">
						<div class="min-h-0">
							We use Stripe to process payments. Stripe accepts all major credit cards, debit cards,
							Apple Pay, and Google Pay!
						</div>
					</div>
				</div>
				<div class="accordion">
					<input type="checkbox" id="toggle-4" class="accordion-toggle" />
					<label for="toggle-4" class="accordion-title">How are images delivered?</label>
					<span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
							><path
								d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"
							/></svg
						>
					</span>
					<div class="accordion-content bg-backgroundSecondary">
						<div class="min-h-0">
							You can directly download images from heroify. Images are scaled to 2x when rendered,
							resulting in a final size of 1024x1024. Your images will be saved so as long as you
							have your license.
						</div>
					</div>
				</div>
				<div class="accordion">
					<input type="checkbox" id="toggle-5" class="accordion-toggle" />
					<label for="toggle-5" class="accordion-title"
						>Can I generate images without a background?</label
					>
					<span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
							><path
								d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"
							/></svg
						>
					</span>
					<div class="accordion-content bg-backgroundSecondary">
						<div class="min-h-0">
							Yes! You can select if you want a background or not when generating an image.
						</div>
					</div>
				</div>
			</div>
		</div>
	</Container>
</Section>
